/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps/web/public/chess.glb -t -o apps/web/components/chess/chess-models.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Highlight: THREE.Mesh;
    HighlightGood: THREE.Mesh;
    HighlightInaccurate: THREE.Mesh;
    HighlightBad: THREE.Mesh;
    f8: THREE.Mesh;
    d8: THREE.Mesh;
    b8: THREE.Mesh;
    g7: THREE.Mesh;
    e7: THREE.Mesh;
    c7: THREE.Mesh;
    a7: THREE.Mesh;
    h6: THREE.Mesh;
    f6: THREE.Mesh;
    d6: THREE.Mesh;
    b6: THREE.Mesh;
    g5: THREE.Mesh;
    e5: THREE.Mesh;
    c5: THREE.Mesh;
    a5: THREE.Mesh;
    h4: THREE.Mesh;
    f4: THREE.Mesh;
    d4: THREE.Mesh;
    b4: THREE.Mesh;
    g3: THREE.Mesh;
    e3: THREE.Mesh;
    c3: THREE.Mesh;
    a3: THREE.Mesh;
    h2: THREE.Mesh;
    f2: THREE.Mesh;
    d2: THREE.Mesh;
    b2: THREE.Mesh;
    g1: THREE.Mesh;
    e1: THREE.Mesh;
    c1: THREE.Mesh;
    a1: THREE.Mesh;
    g8: THREE.Mesh;
    e8: THREE.Mesh;
    c8: THREE.Mesh;
    a8: THREE.Mesh;
    h7: THREE.Mesh;
    f7: THREE.Mesh;
    d7: THREE.Mesh;
    b7: THREE.Mesh;
    g6: THREE.Mesh;
    e6: THREE.Mesh;
    c6: THREE.Mesh;
    a6: THREE.Mesh;
    h5: THREE.Mesh;
    f5: THREE.Mesh;
    d5: THREE.Mesh;
    b5: THREE.Mesh;
    g4: THREE.Mesh;
    e4: THREE.Mesh;
    c4: THREE.Mesh;
    a4: THREE.Mesh;
    h3: THREE.Mesh;
    f3: THREE.Mesh;
    d3: THREE.Mesh;
    b3: THREE.Mesh;
    g2: THREE.Mesh;
    e2: THREE.Mesh;
    c2: THREE.Mesh;
    a2: THREE.Mesh;
    h1: THREE.Mesh;
    f1: THREE.Mesh;
    d1: THREE.Mesh;
    b1: THREE.Mesh;
    frame: THREE.Mesh;
    h8: THREE.Mesh;
    queen: THREE.Mesh;
    king: THREE.Mesh;
    bishop: THREE.Mesh;
    knight: THREE.Mesh;
    rook: THREE.Mesh;
    pawn: THREE.Mesh;
  };
  materials: {
    black: THREE.MeshStandardMaterial;
    highlight: THREE.MeshPhysicalMaterial;
    ['highlight-good']: THREE.MeshPhysicalMaterial;
    ['highlight-inaccurate']: THREE.MeshPhysicalMaterial;
    ['highlight-bad']: THREE.MeshPhysicalMaterial;
    ['black-case']: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chess.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.black} />
      <mesh geometry={nodes.Highlight.geometry} material={materials.highlight} />
      <mesh geometry={nodes.HighlightGood.geometry} material={materials['highlight-good']} />
      <mesh
        geometry={nodes.HighlightInaccurate.geometry}
        material={materials['highlight-inaccurate']}
      />
      <mesh geometry={nodes.HighlightBad.geometry} material={materials['highlight-bad']} />
      <mesh geometry={nodes.f8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.h6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.f6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.h4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.f4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.h2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.f2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.h7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.f7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b7.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a6.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.h5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.f5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b5.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a4.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.h3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.f3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b3.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.g2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.e2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.c2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.a2.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.h1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.f1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.d1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.b1.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.frame.geometry} material={materials.Material} />
      <mesh geometry={nodes.h8.geometry} material={materials['black-case']} />
      <mesh geometry={nodes.queen.geometry} material={materials.white} />
      <mesh geometry={nodes.king.geometry} material={materials.white} />
      <mesh geometry={nodes.bishop.geometry} material={materials.white} />
      <mesh geometry={nodes.knight.geometry} material={materials.white} />
      <mesh geometry={nodes.rook.geometry} material={materials.white} />
      <mesh geometry={nodes.pawn.geometry} material={materials.white} />
    </group>
  );
}

useGLTF.preload('/chess.glb');
